version: '3.8'
services:
  app:
    image: online-stock-management  # ชื่อของ Docker image ของแอปของคุณ
    container_name: go-app-container
    env_file:
      - .env  # โหลดค่าจากไฟล์ .env
    ports:
      - "8080:8080"  # พอร์ตที่ Go app จะเปิดใช้งาน
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
